### ISSUE TITLE
Question about installed extensions in docker container

### ISSUE THREAD

**Issue by IvDmNe** [bmw-software-engineering/foxbox#98]
Hello! Thank you for this standalone fork of FoxGlove. I have one question about extensions. When I used FoxGlove, desktop extensions were installed in `~/.foxglove-studio/extensions` folder, so I could programmatically install them with some bash commands without GUI. Now I want to do something similar with FoxBox, but in Docker container, as It supports this feature. 

I successfully installed my extension via drag-and-drop. And, I suppose, this can be done if I place and unpack content of my `.foxe` file in some folder inside docker container or mount folder with installed extensions from host. However, I could not find a folder in container, where my extension was saved.

Can you give me some hints, where to look for these files?

P.S. It is not a bug. If I choose "quesion" while making an issue, it redirects me to official foxglove discussion

**Comment by aneuwald-ctw** [comment]
Hello @IvDmNe,
Thank you for reaching out! We're glad to hear you're using our fork.

Regarding your question, in the Docker version, we serve the web version of the application. In this version, there is no connection between the software and the `~/.foxglove-studio/extensions` folder because the browser cannot access local folders for security reasons. This functionality is available only in the desktop version.

In the code, this is handled by the `extensionLoaders` variable. The desktop version uses the `new DesktopExtensionLoader(desktopBridge)` component to access the local folder, while the web version uses the `new IdbExtensionLoader("local")`, which reads extensions only from the browser's IndexDB. This is why, if you open another browser, it will not contain any extensions, as the IndexDB is clean.

We may consider implementing this feature in the future, but it is not a priority at the moment. If you are interested, you could try running the Electron app in Docker and share your findings with us, as it would be a valuable contribution to our project!
